# Site settings
title: Vardar Yazılım
email: info@vardar.biz.tr
description: >
  Süreç yönetim sistemi, activworks, bam, bpmn, kpi, süreç danışmanlığı,
  süreç analiz, java, maven, spring, vaadin, activiti, alfresco,
  doküman yönetim sistemi, ayna, nirengi, tagtakip, avaz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.vardar.biz.tr" # the base hostname & protocol for your site
twitter_username: umitvardar
github_username:  vardarltd
facebook_link: vardarltd

# Build settings
markdown: kramdown

# gallerytag:
#     dir: images
#     url: /images
#     thumb_width: 150
#     thumb_height: 150
#     columns: 4
