# Site settings
title: Vardar Yazılım
email: info@vardar.biz.tr
description: >
  Süreç, Proses, yönetim, bpm, bpmn, bpmn2, süreç yönetim sistemi,
  alfresco, doküman yönetim sistemi, document management system,
  activworks, bam, kpi, süreç danışmanlığı, süreç analiz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.vardar.biz.tr" # the base hostname & protocol for your site
twitter_username: umitvardar
github_username:  vardaru
facebook_link: vardarltd

# Build settings
markdown: kramdown

# gallerytag:
#     dir: images
#     url: /images
#     thumb_width: 150
#     thumb_height: 150
#     columns: 4
